### PR TITLE
libs update, couple of new props

### PR DESCRIPTION
**Pull request by mkawczynski07**
Hi.
I updated libs in the project. Alos i added new options:
- `noXaxis`: Boolean - by default is false. To hide X axis,
- `noYaxis`: Boolean - by default is false. To hide Y axis,
- `noXaxisPoints`: Boolean - by default is false. To hide points on X axis,
- `noYaxisPoints`: Boolean - by default is false. To hide points on Y axis,
- `noGridXLines`: Boolean - by default is false. To hide grid X lines,
- `noGridYLines`: Boolean - by default is false. To hide grid Y lines,

I hope that you will update project soon. :)

### CODE REVIEW

**Comment by mkawczynski07** [comment]
I also added  noXlabel and noYlabel props.

**Comment by cedricdelpoux** [comment]
@mkawczynski07 Sorry for the delay. The branch has conflicts. Could you resolve them please ?

**Comment by mkawczynski07** [comment]
@xuopled done. :)

**Comment by cedricdelpoux** [comment]
Thank you :)

**Pull request merged**
